import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import {
  MatButtonModule, MatToolbarModule, MatTableModule, MatMenuModule,
  MatCardModule, MatIconModule, MatLineModule, MatListModule,
  MatSortModule, MatTabsModule, MatChipsModule, MatDividerModule,
  MatInputModule, MatRadioModule, MatPseudoCheckboxModule, MatButtonToggleModule,
  MatCommonModule, MatDialogModule, MatOptionModule, MatRippleModule,
  MatSelectModule, MatSliderModule, MatProgressBarModule, MatTooltipModule,
  MatSidenavModule, MatDatepickerModule, MatPaginatorModule, MatCheckboxModule,
  MatStepperModule, MatAutocompleteModule, MatSlideToggleModule, MatNativeDateModule,
  MatFormFieldModule, MatGridListModule, MatSnackBarModule, MatExpansionModule, MatProgressSpinnerModule
} from '@angular/material';

@NgModule({
  imports: [
    CommonModule,
    MatButtonModule,
    MatToolbarModule,
    MatMenuModule,
    MatCardModule,
    MatIconModule,
    MatLineModule,
    MatListModule,
    MatSortModule,
    MatTabsModule,
    MatChipsModule,
    MatDividerModule,
    MatInputModule,
    MatRadioModule,
    MatPseudoCheckboxModule,
    MatButtonToggleModule,
    MatCommonModule,
    MatDialogModule,
    MatOptionModule,
    MatRippleModule,
    MatSelectModule,
    MatSliderModule,
    MatProgressBarModule,
    MatProgressSpinnerModule,
    MatTooltipModule,
    MatSidenavModule,
    MatDatepickerModule,
    MatPaginatorModule,
    MatCheckboxModule,
    MatStepperModule,
    MatAutocompleteModule,
    MatSlideToggleModule,
    MatNativeDateModule,
    MatFormFieldModule,
    MatGridListModule,
    MatSnackBarModule,
    MatExpansionModule,
    MatTableModule,
  ],
  exports: [
    MatButtonModule,
    MatToolbarModule,
    MatMenuModule,
    MatCardModule,
    MatIconModule,
    MatLineModule,
    MatListModule,
    MatSortModule,
    MatTabsModule,
    MatChipsModule,
    MatDividerModule,
    MatInputModule,
    MatRadioModule,
    MatPseudoCheckboxModule,
    MatButtonToggleModule,
    MatCommonModule,
    MatDialogModule,
    MatOptionModule,
    MatRippleModule,
    MatSelectModule,
    MatSliderModule,
    MatProgressBarModule,
    MatTooltipModule,
    MatSidenavModule,
    MatDatepickerModule,
    MatPaginatorModule,
    MatCheckboxModule,
    MatStepperModule,
    MatAutocompleteModule,
    MatSlideToggleModule,
    MatNativeDateModule,
    MatFormFieldModule,
    MatGridListModule,
    MatSnackBarModule,
    MatExpansionModule,
    MatTableModule,
    MatProgressSpinnerModule
  ],
  declarations: []
})
export class MaterialModule { }
